#  Copyright (C) 2019 Greenweaves Software Limited

#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.

#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.


# BA9C Construct the Suffix Tree of a String 


from snp import ConstructSuffixTreeEdges    



if __name__=='__main__':
    #print('---')
    #for edge in ConstructSuffixTreeEdges('ATAAATG$'):
        #print(edge)
    #print('---')
    Edges = ConstructSuffixTreeEdges('ATCTACCAGCAGTGAACATGGGAGGACCAGTAAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$')   
  
    Expected = [
        '$',
        'ATGGGAGGACCAGTAAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'GCCGCCGCTGG$',
        'C',
        'AAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'CTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'A',
        'GG',
        'GACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'TGGGAGGACCAGTAAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'A',
        'CAGTGAACATGGGAGGACCAGTAAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'TAAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'AG',
        'CTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'C',
        'GCCGCCGCTGG$',
        'TCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'C',
        'ACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'CAGTGAACATGGGAGGACCAGTAAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'AGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'CCAGTAAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'A',
        'CTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'GTGTATAACGCCGCCGCTGG$',
        'G',
        'AAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'GAACATGGGAGGACCAGTAAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'G',
        'T',
        'AACGCCGCCGCTGG$',
        'CTACCAGCAGTGAACATGGGAGGACCAGTAAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'GGAGGACCAGTAAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'TGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'A',
        'T',
        'G',
        'ACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'CAGTGAACATGGGAGGACCAGTAAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'AAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'GAACATGGGAGGACCAGTAAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'G',
        'T',
        'TGGGAGGACCAGTAAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'A',
        'CAGTGAACATGGGAGGACCAGTAAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'TAAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'AG',
        'CTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'CGCTGG$',
        'TGG$',
        'GC',
        'TCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'C',
        'ATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'CGCTGG$',
        'TGG$',
        'CGC',
        'TGG$',
        'C',
        'AGGGTGTATAACGCCGCCGCTGG$',
        'TCGTAGGGTGTATAACGCCGCCGCTGG$',
        'G',
        'T',
        'ACCAGCAGTGAACATGGGAGGACCAGTAAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'ATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'TTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'CG',
        'GG$',
        'TACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'C',
        'T',
        '$',
        'CATGGGAGGACCAGTAAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'GGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'A',
        'CAGTAAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'TCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'C',
        'GGACCAGTAAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'TGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'A',
        'AGTGAACATGGGAGGACCAGTAAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'CGCTGG$',
        'TGG$',
        'CGC',
        'GG$',
        'TACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'C',
        'T',
        '$',
        'AGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'CCAGTAAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'GGACCAGTAAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'A',
        'CTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'AGGACCAGTAAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'TGTATAACGCCGCCGCTGG$',
        'G',
        'TGTATAACGCCGCCGCTGG$',
        'G',
        'AGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'GGGTGTATAACGCCGCCGCTGG$',
        'TAACGCCGCCGCTGG$',
        'A',
        'AACATGGGAGGACCAGTAAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'ATAACGCCGCCGCTGG$',
        'TACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'G',
        'T',
        'ACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'CGTAGGGTGTATAACGCCGCCGCTGG$',
        'G',
        'T',
        'T',
        'CGCCGCCGCTGG$',
        'GGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'A',
        'AGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'AGCAGTGAACATGGGAGGACCAGTAAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'CTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'C',
        'C',
        'GGGTGTATAACGCCGCCGCTGG$',
        'TAACGCCGCCGCTGG$',
        'A',
        'ATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'AGGGTGTATAACGCCGCCGCTGG$',
        'TCGTAGGGTGTATAACGCCGCCGCTGG$',
        'G',
        'T',
        'TACCAGCAGTGAACATGGGAGGACCAGTAAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'C',
        'AACATGGGAGGACCAGTAAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        '$',
        'GAGGACCAGTAAGGAAGGCTTACCCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'G',
        'ATAACGCCGCCGCTGG$',
        'GTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'TACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'G',
        'T',
        'AGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'CCTCGATGTGTTACAGACTCGTTCGTAGGGTGTATAACGCCGCCGCTGG$',
        'AC',
        'T',
        'T',
        'CGTAGGGTGTATAACGCCGCCGCTGG$'
    ]
    
    print ('Expected = {0}, actual={1}'.format(len(Expected),len(Edges)))
    expected = iter(sorted(Expected))
    edges    = iter(sorted(Edges))
    exp      = next(expected)
    ed       = next(edges)
    while exp != '-' and ed !='-':
        if exp<ed:
            print('{0},{1}'.format(exp,'-'))
            exp = next(expected,'-')           
        elif ed<exp:
            print('{0},{1}'.format('-',ed))
            ed = next(edges,'-') 
        else:
            exp = next(expected,'-')
            ed = next(edges,'-')            
            