# Copyright (C) 2019 Greenweaves Software Limited

# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with GNU Emacs.  If not, see <http://www.gnu.org/licenses/>
#
# BA9I Construct the Burrows-Wheeler Transform of a String

def BurrowsWheeler(s):
    def cyclicPermutation(s):
        return s[1:] + s[0:1]

    perms = []
    perm = s
    for i in range(len(s)):
        perm = cyclicPermutation(perm)
        perms.append(perm)
    perms.sort()
    bwt = [perm[-1] for perm in perms]
    return ''.join(bwt)
        
if __name__=='__main__':
    print (BurrowsWheeler('GCGTGCCTGGTCA$'))
    print (BurrowsWheeler('GTCCCCGTTCTCCGATACAGTCTTTGGTCGGGATGAGCGAATCATTTGAAACTACTACTTACGTCCGTTGATGACTTGGCCGCAAATTAAGAGAAATGCTTGATCGACGTGCAAGCGATACTTAGGTGCCGTGGTACATCATGATTGCACTTTCCAAGTCTAGTTTAGGCGAACGGTCGGCGGTACGCCTTCAATCGTGCCCTGTCGAAGGGATCATTGGGAGGCAAGGGCTCTAGCATGTGCTATAGTGAGTACGAGTCGGCACCAGAATCATGTTCGCCGGCGTTACACGACCAACTCGGATTTTAAGTCGACGCTTAAGGATCGGAGTAGCCCGGCACAAACAACATAGCAACTCTGTAGAAATGCCTAGAGCAGGTCATGGTTTACTTGGGCTATAATGATTTAAGCTATTACATCCTTAGCGTAGTGGCGTTTTTCCTTCGGGTTCTATCGACTCATCGTGATATCGGGACGCCCTAAAGCGTAGTAGGCGGGAGTCACTTGGGCAGCGACTTCTACGTCTGCGTCCTCTGACTTGGTTACGACTGGGAAGACCCTATTGCATGGAGTAAACCCGTTCGAGAGGCATTTAGTATAATTCCGAGCAGATGTTAAACCATCGGCCGCTGGCACCACATTGGACCAGTGGCGTCTGTACTCCGCCTAATATGCAGCCATCTACAATATCCAAAATAGCGTAAGCACATTATAAACCTATATGGCCCGGACCCTCTTCCGCAAGGCCCGGAGGGCGCTACTCAGACACTGGCAGCTTTACCGCCACATTACGCAGTGTGATGTAAGAGGTACCACGCTCGTAGCTTTAAGTTCACGACAGATCCACCCTACAGCGAGCACTACACTGCCAAGCCCCATACATCCGAAAACCCTACCACCGCAAGCCGGCTGCTCAGTTCGACGCGTCAAGGACTAAAGAGACCGTATACGAGTTCTAGTAATCTTGCCTCTGTACACTGCAACA$'))
    print (BurrowsWheeler('GCTTCCGCTCTGGAGAGCATCGAAGCCCGGGTTTGCCGACTGGCCATACCGACTCGTTGCAGAGCTATTGATCTGCAGGACGTCATCAATTAGAAGATACTTTACCGGGTCACGGATACGGACATTGCCCATCAAGCGCATCTCCGTGACAAGGACGCGGTTGATCCAGTGCTAGCTTGACTTGTCCTAAACTATGGACCGGCCGCGCGTTTTCGAACATTGTCGGCGTGTTCGTAGGTAACATGCTGTTTTCAGCTGACTTGGCGTATCCGTGCCTTAGGGTCGGATTTGCGTTGTACTATGGAAGATACGATTCGGGTCTCACCTAAATTAGCACTGCGTTGCCTTGGTCTGTAGCATTGGGATGGACAACACAAGAAGTACAAACCTTTGTTTAGCTGGCAAACCGGATTTGATTACCGCTGTAACCCCAAACCTTTTATCAGCTAGTAAATTGCCAATGGATACCCCTCTTCACGAGTTAGGGCCAACCCATGGAAACTTCCCTGTGGTTAAGCTAATCGTAACCGTTTTGGTTAAGTCGCAAGCATACCTAGGGGCACCTAGGTCCTGACACGAAATTTTCACACATAGTTACAGGATTTTCAGGTCAGATGTTTCGGATTCCAGTTGACGTTTTCCCATCGACTGGCTGCTATTGTGAAACTGACTCGACCACTCACACTTTGAATTATCGGCCAAGGAGGCGCCTCACAAAGCGATAACTACAGGTTTCAAGTGTGAACTGGCACTAAACGAATAACGCTCCACACGTGCTACTCGGGTGGACCAAAAAGAATATGCAATGGGGTGTGTATACGGCACTCATGAAATGAGG$'))