#    Copyright (C) 2019 Greenweaves Software Limited
#
#    This is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This software is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with GNU Emacs.  If not, see <http://www.gnu.org/licenses/>
#
# EDIT 	Edit Distance 

from lcsq import dynamic

def edit(s,t):
    def extract(s,t,get_matrix):        
        i = len(s)-1
        j = len(t)-1
        distance=0
        return get_matrix(i,j)
        #while True:
            #if get_matrix(i,j-1) == get_matrix(i,j):
                #j -= 1
                #distance+=1
            #elif get_matrix(i-1,j) == get_matrix(i,j): 
                #i -= 1
                #distance+=1
            #else:
                #assert s[i]==t[j]
                #i -= 1
                #j -= 1
            #if  get_matrix(i,j)==0:
                #return distance
            
    return dynamic([s0 for s0 in s], [t0 for t0 in t],extract)

if __name__=='__main__':
    print (edit('PLEASANTLY','MEANLY'))
    print (edit('QKITNGPGMPGNEDVQQLRPYRNGTWVNVMGCIDMPGHKLHNNWWWWWVYVSIKLNPRVN'
'QSWKMWWHSIEQWTCNGFYCDLVWFMTDLFIVMNHVPTGHNCGQELNLVIMEMNDVDYGW'
'TPDCYRFSSMTHCREHSCPGSTVLYDHMCLNPDLNEGNDDVHYFQACFYTNPWFSICGWH'
'RSELHGRRSERQFFDDVIGQQYIIKPRHSHAWELFYSGSGTTGSSEKRPKEDPRDHGEEG'
'IPNSGMHLIVDQKMCTDPFVHQTTDLVHLYLNQWFCILSWVPSYPACKTRATPNDCHYPC'
'ILKKWKVVEQLPWHMEFSPWDIYVDHLLMHEHSDCGIRSLQREYDFNTTNGWPYWIRADN'
'MIAKPVPYVSVKHFIYQLDDEEKDCIAHQTYQFKGLKKKWNWALNCHMRSILHLLNAVPV'
'RHDCDRDWNDNKHGLQARYKTHKFFDARMFWIRTRCHPAEGDMMWSGKNRVCVTPYENQL'
'TDKESYFKKCSDDCDSRYGMLHTAEHPMKIFLWCYHHVDPRCWNQQKYFAGTCFKAHEPR'
'SCQFYLPQKDPMKIHDRCVYPCDHKREYFQTGTCTCNFENVVMFFDYWQPPPGMWQWAPN'
'DDYIMSQFHFMRKPCDENMMWSECEGTGNINPGLMVNVLILNSCPSESWLPDGQYDLWCL'
'MSCFLYTMAAPANPRRWGNSQKMWKQDMKTMHYFLTQSAWGHYTNFYEPTTKAKFMAINI'
'WFVKGEGIGCGTHHWIQKHLTKMRATCQFSAGTTCCWGKAMEWLAYAFGVKLNILWQINQ'
'WVMDFMTNPTQLNCNNTHVSDSWHQMASIR',
'QKARMVYIAKGMPGNEDVQQLDPYRNGARHVNMMGCGEVDMPPHKLHNNWWWWYVGESIK'
'LNMPDGEAASWKMWWHEQWTCNGCYCDLVWFMTDLFIVMADDFNFQHVELNEMNDVDYTH'
'CYPWTPDCYRFSSMTHCREHSCPGSTILLNPDLNEGNDQYHYKHHSTCFVYQYFQAIFNW'
'MWGTNPWFSICGWHRSELHGRRSERQFFDDVIGQQYIIKPRHSHAWELTGSSEKRPKEDP'
'RDHGEDCDIHGIPNSGMHPIVDQKWCTDPFVHQTTDLVHSWDYIYLEQWFCSWTYFTRAP'
'PNDCHYPCILKKRPVPWHMEDSPWDIYVDHLLVHYHMRTALTADCGICSEGQREYDFNTT'
'NGWPYPIKKDNMIAKPYPYVSVKHFIRQKEDRTSEEDQQCIHQTYQFKGLKHNHLWVNAM'
'FWNALEKPVRHDCDRDWNDNKHGLQARLKTHKFFDARMFWIRNRCHPAEMDMMWSGKNRV'
'CCTAYENQLVCMLMFDKVSYFKKNHFESDDCDSRYAQLHTRESQKKYMHHMRCYHHVTNE'
'FGGPRCWNQQKYCFKAHEFRCCCQFYLTDDRCWKDKDPMKTRHDRCVYPCDHIREYFQTG'
'TCTETDVKCENVVMMWQAGVCHAPNDMRKPCDANMMWSECEGTGNINPGLQVNVLILNSC'
'PSESWNPDGQYDLDCLKSCFVYTMTLIYAPANPRRWGNSHFKMCKQDMKRRQQGRDTVDQ'
'GLPHYFLTQSARGFCQPKFYTYEPTTKAKFMAILLHVGGCLIWFVKGEGIGCGTHWWINF'
'HHSNKHLMRARTEVPRCQFSAGWGHMRQSGTCCWGKAMDWLAYAFGVKVWRKNVLPLNML'
'AQINQWVMNNTHVSDSWHFMASIR'))